# Generated by Django 3.2.11 on 2022-01-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_configuration_shipping_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='default_shipping_enabled',
            field=models.BooleanField(default=False, help_text='Whether to enable default shipping.\nThis essentially means you ship to all countries,\nnot only those with configured shipping rates'),
        ),
    ]
