# Generated by Django 2.2.17 on 2020-12-22 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('value_absolute', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('value_percent', models.SmallIntegerField(default=0)),
                ('validity_start', models.DateTimeField()),
                ('validity_end', models.DateTimeField(blank=True, null=True)),
                ('usage_max', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BasketCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket_id', models.CharField(max_length=32, unique=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coupons.Coupon')),
            ],
        ),
    ]
