# Generated by Django 5.2.16 on 2026-07-25 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_alter_shippingrateprocessor_polymorphic_ctype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingrateprocessor',
            options={},
        ),
    ]
