# Generated by Django 2.2.17 on 2020-12-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='keep_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='keep_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
